---
title: "Homework 5"
author: "Mohamed Alhassan"
date: "2022-11-30"
output: pdf_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, message =  FALSE, warning =  FALSE, error = FALSE)
```


# Choice 2

## Cleaning the data

```{r}
library(tinytex)
library(tidyverse)
library(lubridate)

homicides <- read_csv("../data/homicide-data.csv") %>% 
  filter(city == "Baltimore") %>% 
  mutate(reported_date = ymd(reported_date)) %>% 
  separate(col = reported_date, into = c("year", "month", "day"), sep = "-") %>% 
  select(-day) %>%
  unite(col = reported_date, year, month, sep = "-") %>% 
  group_by(reported_date) %>% 
  summarize(total = n()) %>% 
  mutate(reported_date = ym(reported_date))
```

## Cleaning the data for graph

```{r}
library(ggplot2)
library(ggthemes)

gray <- read_csv("../data/homicide-data.csv") %>% 
  filter(uid == "Bal-003523") %>%
  mutate(reported_date = ymd(reported_date)) %>% 
  separate(col = reported_date, into = c("year", "month", "day"), sep = "-") %>% 
  unite(col = reported_date, year, month, sep = "-") %>% 
  mutate(reported_date = ym(reported_date)) %>% 
  select(reported_date) 


homicide_logical <- str_detect(homicides$reported_date, "20..-[0-1][^1-4]")

homicides$season <- homicide_logical

homicides <- homicides %>%
  mutate(season = as_factor (x = season),
         season = fct_recode(season, Summer = "TRUE",
                             Winter = "FALSE"),
         season = fct_reorder(season, total, .desc = TRUE))
```

## Graph

```{r, fig.dim = c(11, 3.5)}
homicides %>%
  ggplot(aes(x = reported_date, y = total)) +
  geom_col(mapping = aes(fill = season)) +
  geom_smooth(method = "loess", span = 0.1, se = FALSE) +
  scale_fill_manual(values = c("#d3d3d3", "#add8e6")) +
  guides(fill = guide_legend(title = "")) +
  geom_vline(xintercept = gray$reported_date,
             linetype = 2,
             linewidth = 1.5,
             color = "red") +
  labs(y = "Monthly homicides", x = "Date", title = "Homicides in Baltimore, MD") +
  theme_dark() +
  theme(legend.position = "bottom") +
  geom_text(data = homicides[100,],
            label = "Arrest of \n Freddie Gray",
            vjust = -2,
            hjust = 1.1,
            color = "white")
```

